Endpoint: Trigger SSA
filecoin-project/filplus-backend pull request #188
Opened 2024-05-17 15:49 UTC by Filip-L

## Endpoint: application/trigger_ssa

**Description:**
The `application/trigger_ssa` endpoint checks, based on the data received (`TriggerSSAInfo`), the current state of the application. If the conditions are met, it calls the `refill` function.

**Usage Conditions:**
To execute this endpoint, the following conditions must be met:
1. The application must be in the `Granted` state.
2. The Last active allocation ID must not be active.
3. The total allocated amount can't be greater than or equal to the total requested amount.

**Impact on Application Lifecycle:**
It will add a comment on the relevant GitHub issue and change the label to `refill`.

**Deployment Considerations:**
No special actions are required.

**Example TriggerSSAInfo:**
```json
{
  "id": "client_address",
  "owner": "owner_name",
  "repo": "repo_name",
  "amount": "1",
  "amount_type": "PiB"
}

2024-05-17 15:55 UTC, willscott approved these changes

2024-05-20 09:40 UTC, kacperzuk-neti requested changes

2024-05-20 09:40 UTC, kacperzuk-neti commented on fplus-lib/src/core/mod.rs
> +        if requested_so_far >= total_requested {
```suggestion
        if requested_so_far + ssa_amount >= total_requested {
```
Where `ssa_amount` is info.amount converted to bytes.

2024-05-20 13:00 UTC, kacperzuk-neti commented
Superseded by https://github.com/filecoin-project/filplus-backend/pull/189

2024-05-20 13:00 UTC, closed without merging